-- MySQL Script generated by MySQL Workbench
-- Sun Mar 22 15:21:46 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bi_kamar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bi_kamar` ;
CREATE SCHEMA IF NOT EXISTS `bi_kamar` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bi_kamar` ;

-- -----------------------------------------------------
-- Table `bi_kamar`.`d_date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bi_kamar`.`d_date` ;

CREATE TABLE IF NOT EXISTS `bi_kamar`.`d_date` (
  `dateid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `day` TINYINT UNSIGNED NOT NULL,
  `month` TINYINT UNSIGNED NOT NULL,
  `year` SMALLINT UNSIGNED NOT NULL,
  `trimester` TINYINT UNSIGNED NOT NULL,
  `semester` TINYINT UNSIGNED NOT NULL,
  `dayOfWeek` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`dateid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bi_kamar`.`d_seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bi_kamar`.`d_seller` ;

CREATE TABLE IF NOT EXISTS `bi_kamar`.`d_seller` (
  `sellerid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `externalid` INT NULL,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`sellerid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bi_kamar`.`d_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bi_kamar`.`d_product` ;

CREATE TABLE IF NOT EXISTS `bi_kamar`.`d_product` (
  `productid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `externalid` INT NULL,
  `name` VARCHAR(200) NOT NULL,
  `manufacturer` VARCHAR(100) NOT NULL,
  `distributor` VARCHAR(100) NOT NULL,
  `category` VARCHAR(100) NOT NULL,
  `line` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`productid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bi_kamar`.`d_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bi_kamar`.`d_client` ;

CREATE TABLE IF NOT EXISTS `bi_kamar`.`d_client` (
  `clientid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `externalid` INT NULL,
  `name` VARCHAR(300) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `neighborhood` VARCHAR(45) NOT NULL,
  `zip` VARCHAR(10) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `district` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`clientid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bi_kamar`.`f_sale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bi_kamar`.`f_sale` ;

CREATE TABLE IF NOT EXISTS `bi_kamar`.`f_sale` (
  `salesid` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `externalid` VARCHAR(15) NOT NULL,
  `quantity` DECIMAL(9,3) NOT NULL,
  `total` DECIMAL(12,2) NOT NULL,
  `profit` DECIMAL(12,2) NOT NULL,
  `discount` DECIMAL(12,2) NOT NULL,
  `d_date_dateid` INT UNSIGNED NOT NULL,
  `d_seller_sellerid` INT UNSIGNED NOT NULL,
  `d_product_productid` INT UNSIGNED NOT NULL,
  `d_client_clientid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`salesid`),
  INDEX `fk_f_sales_d_date1_idx` (`d_date_dateid` ASC),
  INDEX `fk_f_sales_d_seller1_idx` (`d_seller_sellerid` ASC),
  INDEX `fk_f_sales_d_product1_idx` (`d_product_productid` ASC),
  INDEX `fk_f_sale_d_client1_idx` (`d_client_clientid` ASC),
  CONSTRAINT `fk_f_sales_d_date1`
    FOREIGN KEY (`d_date_dateid`)
    REFERENCES `bi_kamar`.`d_date` (`dateid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_f_sales_d_seller1`
    FOREIGN KEY (`d_seller_sellerid`)
    REFERENCES `bi_kamar`.`d_seller` (`sellerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_f_sales_d_product1`
    FOREIGN KEY (`d_product_productid`)
    REFERENCES `bi_kamar`.`d_product` (`productid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_f_sale_d_client1`
    FOREIGN KEY (`d_client_clientid`)
    REFERENCES `bi_kamar`.`d_client` (`clientid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bi_kamar`.`etl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bi_kamar`.`etl` ;

CREATE TABLE IF NOT EXISTS `bi_kamar`.`etl` (
  `etlid` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NOT NULL,
  `completed` TINYINT UNSIGNED NULL,
  PRIMARY KEY (`etlid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bi_kamar`.`mgr_d_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bi_kamar`.`mgr_d_client` ;

CREATE TABLE IF NOT EXISTS `bi_kamar`.`mgr_d_client` (
  `d_client_clientid` INT UNSIGNED NOT NULL,
  `source` VARCHAR(4) NOT NULL,
  `externalid` INT NOT NULL,
  `crc32` VARCHAR(8) NOT NULL,
  INDEX `fk_mgr_d_client_d_client1_idx` (`d_client_clientid` ASC),
  PRIMARY KEY (`source`, `externalid`),
  CONSTRAINT `fk_mgr_d_client_d_client1`
    FOREIGN KEY (`d_client_clientid`)
    REFERENCES `bi_kamar`.`d_client` (`clientid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bi_kamar`.`mgr_d_seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bi_kamar`.`mgr_d_seller` ;

CREATE TABLE IF NOT EXISTS `bi_kamar`.`mgr_d_seller` (
  `d_seller_sellerid` INT UNSIGNED NOT NULL,
  `source` VARCHAR(4) NOT NULL,
  `externalid` INT NOT NULL,
  `crc32` VARCHAR(8) NOT NULL,
  INDEX `fk_mgr_d_seller_d_seller1_idx` (`d_seller_sellerid` ASC),
  PRIMARY KEY (`source`, `externalid`),
  CONSTRAINT `fk_mgr_d_seller_d_seller1`
    FOREIGN KEY (`d_seller_sellerid`)
    REFERENCES `bi_kamar`.`d_seller` (`sellerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bi_kamar`.`mgr_d_product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bi_kamar`.`mgr_d_product` ;

CREATE TABLE IF NOT EXISTS `bi_kamar`.`mgr_d_product` (
  `d_product_productid` INT UNSIGNED NOT NULL,
  `source` VARCHAR(4) NOT NULL,
  `externalid` INT NOT NULL,
  `crc32` VARCHAR(8) NOT NULL,
  INDEX `fk_mgr_d_product_d_product1_idx` (`d_product_productid` ASC),
  PRIMARY KEY (`source`, `externalid`),
  CONSTRAINT `fk_mgr_d_product_d_product1`
    FOREIGN KEY (`d_product_productid`)
    REFERENCES `bi_kamar`.`d_product` (`productid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bi_kamar`.`d_wstation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bi_kamar`.`d_wstation` ;

CREATE TABLE IF NOT EXISTS `bi_kamar`.`d_wstation` (
  `wstationid` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(3) NOT NULL,
  `wmo` VARCHAR(6) NOT NULL,
  `icao` VARCHAR(4) NOT NULL,
  `station` VARCHAR(45) NOT NULL,
  `latitude` TINYINT NULL,
  `longitude` TINYINT NULL,
  `height` SMALLINT NULL,
  PRIMARY KEY (`wstationid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bi_kamar`.`f_synop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bi_kamar`.`f_synop` ;

CREATE TABLE IF NOT EXISTS `bi_kamar`.`f_synop` (
  `synopid` INT NOT NULL AUTO_INCREMENT,
  `wind_dir` SMALLINT UNSIGNED NOT NULL,
  `wind_speed` DECIMAL(6,2) NOT NULL,
  `precipitation` SMALLINT UNSIGNED NOT NULL,
  `dryBulbC` DECIMAL(5,2) NOT NULL,
  `dewPointC` DECIMAL(5,2) NOT NULL,
  `d_wstation_wstationid` INT NOT NULL,
  `d_date_dateid` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`synopid`),
  INDEX `fk_f_synop_d_wstation1_idx` (`d_wstation_wstationid` ASC),
  INDEX `fk_f_synop_d_date1_idx` (`d_date_dateid` ASC),
  CONSTRAINT `fk_f_synop_d_wstation1`
    FOREIGN KEY (`d_wstation_wstationid`)
    REFERENCES `bi_kamar`.`d_wstation` (`wstationid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_f_synop_d_date1`
    FOREIGN KEY (`d_date_dateid`)
    REFERENCES `bi_kamar`.`d_date` (`dateid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
